PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMMTT_HIST_PART CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMMTT_HIST_PART-PROYECTO .
    FIELD ZMMTT_HIST_PART-ELEMENTO_PEP .
    FIELD ZMMTT_HIST_PART-PROVEEDOR .
    FIELD ZMMTT_HIST_PART-FACTURA .
    FIELD ZMMTT_HIST_PART-DESC_PROYECTO .
    FIELD ZMMTT_HIST_PART-CLAS_CARATULA .
    FIELD ZMMTT_HIST_PART-T_REGISTRO .
    FIELD ZMMTT_HIST_PART-CLAS_PARTIDA .
    FIELD ZMMTT_HIST_PART-F_CONTABILIZACION .
    FIELD ZMMTT_HIST_PART-N_PROVEEDOR .
    FIELD ZMMTT_HIST_PART-D_FACTURA .
    FIELD ZMMTT_HIST_PART-T_CABECERO .
    FIELD ZMMTT_HIST_PART-IMPORTE .
    FIELD ZMMTT_HIST_PART-MONEDA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMMTT_HIST_PART-PROYECTO .
    FIELD ZMMTT_HIST_PART-ELEMENTO_PEP .
    FIELD ZMMTT_HIST_PART-PROVEEDOR .
    FIELD ZMMTT_HIST_PART-FACTURA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
