*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMMTT_FUSION_SOCTOP.              " Global Data
  INCLUDE LZMMTT_FUSION_SOCUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMMTT_FUSION_SOCF00                    . " subprograms
  INCLUDE LZMMTT_FUSION_SOCI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMMTT_FUSION_SOCF...              " Subprograms
* INCLUDE LZMMTT_FUSION_SOCO...              " PBO-Modules
* INCLUDE LZMMTT_FUSION_SOCI...              " PAI-Modules
