PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMMTT_30_HJSRV_H CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMMTT_30_HJSRV_H-IDRFC .
    FIELD ZMMTT_30_HJSRV_H-EBELN .
    FIELD ZMMTT_30_HJSRV_H-LIFNR .
    FIELD ZMMTT_30_HJSRV_H-WAERS .
    FIELD ZMMTT_30_HJSRV_H-STSH .
    FIELD ZMMTT_30_HJSRV_H-DATE_EXEC .
    FIELD ZMMTT_30_HJSRV_H-TIME_EXEC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMMTT_30_HJSRV_H-IDRFC .
    FIELD ZMMTT_30_HJSRV_H-EBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
