PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMMTT_30_HJSRV_D CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMMTT_30_HJSRV_D-IDRFC .
    FIELD ZMMTT_30_HJSRV_D-EBELN .
    FIELD ZMMTT_30_HJSRV_D-EBELP .
    FIELD ZMMTT_30_HJSRV_D-EXTROW .
    FIELD ZMMTT_30_HJSRV_D-ASNUM .
    FIELD ZMMTT_30_HJSRV_D-ERFMG .
    FIELD ZMMTT_30_HJSRV_D-PRCTG .
    FIELD ZMMTT_30_HJSRV_D-MSGERR .
    FIELD ZMMTT_30_HJSRV_D-BKTXT .
    FIELD ZMMTT_30_HJSRV_D-BILL .
    FIELD ZMMTT_30_HJSRV_D-XBLNR .
    FIELD ZMMTT_30_HJSRV_D-STSD .
    FIELD ZMMTT_30_HJSRV_D-LBLNI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMMTT_30_HJSRV_D-IDRFC .
    FIELD ZMMTT_30_HJSRV_D-EBELN .
    FIELD ZMMTT_30_HJSRV_D-EBELP .
    FIELD ZMMTT_30_HJSRV_D-EXTROW .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
