PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMMTT_0040_CH_OR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMMTT_0040_CH_OR-PROYECTO .
    FIELD ZMMTT_0040_CH_OR-FOLIO .
    FIELD ZMMTT_0040_CH_OR-TIPO_SOL .
    FIELD ZMMTT_0040_CH_OR-FECHA_REGISTRO .
    FIELD ZMMTT_0040_CH_OR-AFECTA .
    FIELD ZMMTT_0040_CH_OR-FECHA_SOLICITUD .
    FIELD ZMMTT_0040_CH_OR-SOLICITANTE .
    FIELD ZMMTT_0040_CH_OR-CARGO_Y_EMPRESA .
    FIELD ZMMTT_0040_CH_OR-ELABORO .
    FIELD ZMMTT_0040_CH_OR-CARGO_EMPRESA_E .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_01 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_02 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_03 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_04 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_05 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_06 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_07 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_08 .
    FIELD ZMMTT_0040_CH_OR-MOTIVO_09 .
    FIELD ZMMTT_0040_CH_OR-OBSERVACIONES .
    FIELD ZMMTT_0040_CH_OR-IMPACTO_PROGRAMA .
    FIELD ZMMTT_0040_CH_OR-ATRASO .
    FIELD ZMMTT_0040_CH_OR-FECHA_TERMINO .
    FIELD ZMMTT_0040_CH_OR-DESCRIPCION .
    FIELD ZMMTT_0040_CH_OR-IMPACTO_PLANOS .
    FIELD ZMMTT_0040_CH_OR-N_FECHA_TER .
    FIELD ZMMTT_0040_CH_OR-CARGO_A .
    FIELD ZMMTT_0040_CH_OR-IMPORTE_AU .
    FIELD ZMMTT_0040_CH_OR-FECHA_EJEC .
    FIELD ZMMTT_0040_CH_OR-HORA_EJEC .
    FIELD ZMMTT_0040_CH_OR-ID_OBJETO1 .
    FIELD ZMMTT_0040_CH_OR-ID_OBJETO2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMMTT_0040_CH_OR-PROYECTO .
    FIELD ZMMTT_0040_CH_OR-FOLIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
